### ISSUE TITLE
zsh bus error since Ethereal 13.70

### ISSUE THREAD

**Issue by microsmeta** [AndyGrant/EtherealDev#2]
Hi Andrew,
on Mac Silicon M1  the build 13.69 June, 1 works perfectly. Since 13.70 June, 3 up to 13.80 it compiles, it calculates for a while then crashes.

https://github.com/AndyGrant/EtherealDev/tree/60f4d5c58672aac237bf65aa6d00363c25f99734

Thank you!

**Comment by AndyGrant** [comment]
I do not have support for Apple processors at this time. The fact that you were able to run a branch at all is surprising. Ultimately I will not address the issue, as I do not own any Apple products, nor do I have any intention on support them. Sorry for the trouble.

**Comment by microsmeta** [comment]
> I do not have support for Apple processors at this time. The fact that you were able to run a branch at all is surprising. Ultimately I will not address the issue, as I do not own any Apple products, nor do I have any intention on support them. Sorry for the trouble.

You are welcome!

It's a very good and resilient engine that I adore since years. Even only the 13.xx github version without NNUE Is 3400 ELO and I have just managed to port the 2020's Etherlito with last 2020 SF 21 MB NNUE on Mac M1!  Close to 2022's  Berserk 9 and Koivisto 8.13 (testing all 3 right now on Mac M1)

Thank you very much!!!

Alex

Last login: Wed Aug 10 19:17:57 on ttys001
Etherlito-master/src/Etherlito ; exit;                 

uci        
id name Ethereal 12.69 (POPCNT)
id author Andrew Grant, Alayan & Laldon
option name Hash type spin default 16 min 2 max 131072
option name Threads type spin default 1 min 1 max 2048
option name MultiPV type spin default 1 min 1 max 256
option name ContemptDrawPenalty type spin default 0 min -300 max 300
option name ContemptComplexity type spin default 0 min -100 max 100
option name MoveOverhead type spin default 100 min 0 max 10000
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 0 min 0 max 127
option name Ponder type check default false
option name AnalysisMode type check default false
option name UCI_Chess960 type check default false
uciok

go infinite
info depth 1 seldepth 1 multipv 1 score cp -3 time 0 nodes 5 nps 5000 tbhits 0 hashfull 0 pv g1f3 
info depth 2 seldepth 2 multipv 1 score cp 25 time 0 nodes 17 nps 17000 tbhits 0 hashfull 0 pv g1f3 a7a6 
info depth 3 seldepth 3 multipv 1 score cp -21 time 1 nodes 84 nps 42000 tbhits 0 hashfull 0 pv g1f3 g8f6 a2a3 
info depth 4 seldepth 5 multipv 1 score cp 31 time 1 nodes 212 nps 106000 tbhits 0 hashfull 0 pv d2d4 g8f6 a2a3 c7c6 
info depth 5 seldepth 6 multipv 1 score cp 0 time 4 nodes 764 nps 152000 tbhits 0 hashfull 0 pv d2d4 g8f6 c1g5 e7e6 g5f6 d8f6 
info depth 6 seldepth 5 multipv 1 score cp 1 time 8 nodes 1400 nps 155000 tbhits 0 hashfull 0 pv d2d4 g8f6 d4d5 a7a6 a2a3 
info depth 7 seldepth 9 multipv 1 score cp 7 time 13 nodes 3080 nps 220000 tbhits 0 hashfull 0 pv e2e4 e7e5 d2d4 e5d4 d1d4 g8f6 b1c3
