### ISSUE TITLE
connecting the Ethernet Client to the Server on Same ENC28J60 Device Fails

### ISSUE THREAD

**Issue by fatmehosseini** [AndyGrant/EtherealDev#3]
I am encountering an issue when trying to run both an Ethernet server and an Ethernet client on the same ESP32 device using the EthernetENC library with an ENC28J60 module. While individually, both the client and server functionality work as expected, they fail to operate simultaneously. 

Observed Behavior:
- The client fails to connect to the server running on the same ENC28J60-based ESP32.
- The server does not register the incoming connection.
- Debugging suggests packets are not properly routed back to the server.

Expected Behavior:
The Ethernet client and server on the same ESP32 should be able to communicate over the ENC28J60 hardware.

- Hardware: ESP32 with ENC28J60 Ethernet Module
- Network Setup: Direct connection to ENC28J60 without an external switch/router (client and server on same device).

I would appreciate your thoughts on addressing this limitation or guidance on implementing a workaround within the library.

**Comment by AndyGrant** [comment]
I do believe you have the wrong repository. This is a chess program.

**Comment by fatmehosseini** [comment]
Oh! sorry, my bad!
